### ISSUE TITLE
where do you get kerberos traffic?

### ISSUE THREAD

**Issue by duzvik** [0Kee-Team/WatchAD#1]
I saw in the diagram kerberos traffic. 
Where do you get kerberos traffic?  Seems packetbeat not suitable for this.

**Comment by Qianlitp** [comment]
Yes, packetbeat does not support the kerberos protocol.
I developed a module to parse the kerberos protocol by reference to [gokrb5](https://github.com/jcmturner/gokrb5) and added it to packetbeat.
But it is not currently in this project, I will consider open source in the future.

**Comment by duzvik** [comment]
Does your kerberos module parse packets and send  to logstash for future analysis following message types:
11: KRB_AS_REP
12: KRB_TGS_REQ
13: KRB_TGS_REP
14: KRB_AP_REQ
32: KRB_AP_ERR_TKT_EXPIRED

**Comment by duzvik** [comment]
Seems yes: https://github.com/0Kee-Team/WatchAD/blob/3a04631a725d94b8bbf583b2a73c09d375a8383b/models/Kerberos.py#L15-L21

It makes sense. I understand. Thank you.
