### ISSUE TITLE
能否告知rabbitmq等需要的配置 

### ISSUE THREAD

**Issue by jack-fox-gif** [0Kee-Team/WatchAD#11]
目前check时，报错pika.exceptions.ConnectionClosedByBroker: (530, "NOT_ALLOWED - access to vhost '/' refused for user 'WatchAD'")
2019-11-13 16:06:17,138 - WatchAD - ERROR - Can't connect to the MQ, please reconfirm the settings.
，无法连接MQ，已在rabbitmq上增加了WatchAD/WatchAD-by-0KEE,端口5672和15672都是打开的，谢谢！

**Comment by Qianlitp** [comment]
你的rabbitmq是自己搭建的服务，然后自定义添加用户的吗？  请参考添加权限，[RabbitMQ用户角色及权限控制](https://blog.csdn.net/zyz511919766/article/details/42292655)

如果你的 rabbitmq 已经存在高权限的账户，可以直接修改下面的两处配置：
https://github.com/0Kee-Team/WatchAD/blob/15ce690a54b1e097643309855d478f07f22f4f36/settings/database_config.py#L64-L74

https://github.com/0Kee-Team/WatchAD/blob/15ce690a54b1e097643309855d478f07f22f4f36/settings/logstash/logstash.conf#L26-L35

**Comment by jack-fox-gif** [comment]
非常感谢，服务都是我自己搭建的，修改上面的配置后，已check成功。

**Comment by PoolHell** [comment]
你好，我docker-compuse up时，显示如下错误
![image](https://user-images.githubusercontent.com/18211519/71339708-3c461b80-258f-11ea-81a9-5f979f549f04.png)
请问，这是哪里导致的呢？
