### ISSUE TITLE
Docker version 19.03.2  error

### ISSUE THREAD

**Issue by Junm0** [0Kee-Team/WatchAD#13]
Pulling watchad_rabbitmq (rabbitmq:management)...
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 80, in _execute
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 93, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 354, in ensure_image_exists
  File "compose/service.py", line 1222, in pull
  File "compose/progress_stream.py", line 102, in get_digest_from_pull
  File "compose/service.py", line 1187, in _do_pull
  File "site-packages/docker/api/image.py", line 381, in pull
  File "site-packages/docker/auth.py", line 48, in get_config_header
  File "site-packages/docker/auth.py", line 322, in resolve_authconfig
  File "site-packages/docker/auth.py", line 235, in resolve_authconfig
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".',)
[34147] Failed to execute script docker-compose

**Comment by Qianlitp** [comment]
你的 docker-compose 安装有问题，请参照[官方文档](https://docs.docker.com/compose/install/)解决。

**Comment by Junm0** [comment]
谢谢，有没有生产环境安装文档




            
            
                
                    
                            
                                
                            
                            
                                xue zhichao
                            
                    
                        
                            
                                    邮箱：xuezhichao58@gmail.com
                            
                        
                
            
        


On 11/29/2019 17:08, 9ian1i wrote: Closed #13.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/0Kee-Team/WatchAD/issues/13?email_source=notifications\u0026email_token=ANU4PLMMAN36TMMKYDDYHS3QWDLYZA5CNFSM4JST4AYKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVFJLNDA#event-2840770188",
"url": "https://github.com/0Kee-Team/WatchAD/issues/13?email_source=notifications\u0026email_token=ANU4PLMMAN36TMMKYDDYHS3QWDLYZA5CNFSM4JST4AYKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVFJLNDA#event-2840770188",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Qianlitp** [comment]
生产环境指需要稳定可用的存储及中间件服务，你可以选择自己搭建或者使用你们公司内部的现有服务。
这一般根据你的生产环境规模决定，如果你的域拥有数千台办公机：
rabbitmq、redis、mongodb和logstash 全部安装到一台8核16G服务器就可以基础的稳定服务。

至于ES需要拥有较稳定的写入和读取性能，拥有足够的存储空间（根据你的日志保留时间，一般不低于**1TB**）。

**Comment by Junm0** [comment]
学到了，thx




            
            
                
                    
                            
                                
                            
                            
                                xue zhichao
                            
                    
                        
                            
                                    邮箱：xuezhichao58@gmail.com
                            
                        
                
            
        


On 12/12/2019 18:20, 9ian1i wrote: 生产环境指需要稳定可用的存储及中间件服务，你可以选择自己搭建或者使用你们公司内部的现有服务。
这一般根据你的生产环境规模决定，如果你的域拥有数千台办公机：
rabbitmq、redis、mongodb和logstash 全部安装到一台8核16G服务器就可以基础的稳定服务。
至于ES需要拥有较稳定的写入和读取性能，拥有足够的存储空间（根据你的日志保留时间，一般不低于1TB）。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/0Kee-Team/WatchAD/issues/13?email_source=notifications\u0026email_token=ANU4PLIZON2S6CXFCLM4QY3QYIF5TA5CNFSM4JST4AYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGWFVZI#issuecomment-564943589",
"url": "https://github.com/0Kee-Team/WatchAD/issues/13?email_source=notifications\u0026email_token=ANU4PLIZON2S6CXFCLM4QY3QYIF5TA5CNFSM4JST4AYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGWFVZI#issuecomment-564943589",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
