### ISSUE TITLE
pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by jianbin-lv** [0Kee-Team/WatchAD#14]
安装失败，是需要特殊的pip源地址吗？提示No matching distribution found for pika==1.0.0

**Comment by Qianlitp** [comment]
应该是不需要的，你使用的python版本和系统类型呢？

**Comment by jianbin-lv** [comment]
这个问题我已经解决了，我的代理没设置。我的Server2012R2的服务器，安装winlogbeat后服务无法启动，报错1053。我用的6.2.4版本的winlogbeat，请帮忙分析原因额。



---Original---

**Comment by Qianlitp** [comment]
是winlogbeat报错无法启动吗，具体的错误日志信息呢。

无法启动一般是由于配置文件有问题，我给了参考的配置文件，修改其中的HOST为你的logstash地址即可。

**Comment by jianbin-lv** [comment]
这都只能监控单个域控服务器吗？我要监控28个域控，需要怎么配置。我在初始化引擎的时候老是提示我认证不对，这个执行安装命令通不过。

**Comment by Qianlitp** [comment]
是LDAP认证不对吗，首先你得在对应的域上创建一个普通域账号，安装时，指定使用的LDAP服务的IP（某一台域控，确保网络能通），输入正确的账号密码。

**Comment by Qianlitp** [comment]
目前对**同一个域下的域控数量没有限制**，但多域环境没有进行完整测试，可能存在问题。

**Comment by jianbin-lv** [comment]
普通域账号吗？需不需要相关的权限，我输的超级用户额



---Original---

**Comment by Qianlitp** [comment]
普通域账号即可查询LDAP，无需其它的权限。

**Comment by jianbin-lv** [comment]
安装web时提示Service "frontend" 建立失败，返回非0值1



---Original---

**Comment by Qianlitp** [comment]
还请贴出具体的错误信息，web相关可以在另一个项目新开issue
