### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by PoolHell** [0Kee-Team/WatchAD#16]
请问，安装本地测试环境的话，对系统有什么要求吗，我部署了几天，总是有不同的错误，至今都没有成功，我运行docker-compose up后，查看es的启动日志，总是显示max virtual memory areas vm.max_map_count 65530 is too low,网上的方法也不见好使，请问这到底是哪里的问题？
我是在虚拟机win server 2008中部署的。
感激不尽

**Comment by Qianlitp** [comment]
WatchAD 只能安装在linux系统上，如果你安装本地测试环境且使用虚拟机，建议分配**8G**的内存（因服务依赖较多）。

WatchAD 的数据采集终端  winlogbeat 安装在域控（win server）上。

**Comment by PoolHell** [comment]
哦，大概了解了，如果我只是安装本地的测试环境的话，就只在win server 2008一台机器上装就行了是吧。

**Comment by PoolHell** [comment]
您意思是说，运行docker-compose up这个命令也是在Linux系统上吗？

**Comment by Qianlitp** [comment]
是的 ，这些存储服务肯定是安装在linux上更加稳定，不建议使用win server

**Comment by PoolHell** [comment]
好的，感谢百忙之中抽空解惑，感激不尽。
