### ISSUE TITLE
docker启动之后logstash端口未映射

### ISSUE THREAD

**Issue by 4mazing** [0Kee-Team/WatchAD#17]
docker-compose up，无报错等其他情况，端口是没有映射出来么？直接telnet端口是拒绝状态，如图所示：  

![TIM图片20191217150420](https://user-images.githubusercontent.com/22395846/70972521-871ee980-20de-11ea-9701-195232aec4eb.png)

使用WatchAD-web也在一台机子上运行后，访问只有nginx欢迎页面，不是预想的那个dashboard，是因为配置问题吗？引擎和web都是在一台linux服务器，性能应该是没问题的。可能有其他原因嘛？

**Comment by Qianlitp** [comment]
logstagh使用的网络模式为：HOST，即使用宿主机网络环境，你尝试telnet本机的5044端口试试，而不是访问docker网络。

WatchAD-Web请访问 /activity_timeline.html 进入威胁列表页面。（dashboard.html页面暂时没做）

**Comment by Qianlitp** [comment]
在宿主机下telnet 127.0.0.1 5044

**Comment by 4mazing** [comment]
试了，端口看着像是通了，但是直接就被**Connection closed by foreign host**，这也是不正常的吧？

![image](https://user-images.githubusercontent.com/22395846/70973890-8b003b00-20e1-11ea-836e-9d0a3df2e7e9.png)

**Comment by Qianlitp** [comment]
接下来按照文档安装winlogbeat，地址指向logstash，观察ES和mq中是否有数据产生即可。

**Comment by 4mazing** [comment]
嗯，上面的配置都做了，看到es里面是有数据了应该，现在的问题是想要通过watchAD-web接入，但是npm一直编译不过去，想问一下这个源的问题是怎么配置。

![image](https://user-images.githubusercontent.com/22395846/71050871-62c81900-2181-11ea-856e-b79c30a61a4d.png)

**Comment by Qianlitp** [comment]
这个是用的淘宝的源，你可以直接修改此处：
https://github.com/0Kee-Team/WatchAD-Web/blob/3de23e75c97d6fccd486891397d3d22d26f6d800/frontend/Dockerfile#L9
将 --registry 往后都删除，只留下 RUN npm install

**Comment by 4mazing** [comment]
淘宝的源问题是因为我通过dockerfile的时候dns解析不了所以没办法，换了个机器可以了。新问题配置了database.conf文件之后，启动web访问是nginx欢迎页面。

![image](https://user-images.githubusercontent.com/22395846/71063118-0c6dd100-21a7-11ea-96fc-46682e5dc341.png)

引擎是启动了

![image](https://user-images.githubusercontent.com/22395846/71063303-6ff7fe80-21a7-11ea-9a4a-eeb7b25fb49a.png)

请教一下是哪里出问题了

**Comment by Qianlitp** [comment]
这个地方是我没有说清楚，直接访问 /activity_timeline.html
