### ISSUE TITLE
安装的Docker 镜像包在哪里下载？

### ISSUE THREAD

**Issue by santosshen** [0Kee-Team/WatchAD#5]
安装的Docker 镜像包在哪里下载？

**Comment by Qianlitp** [comment]
抱歉，我没有理解你的意思。

WatchAD依赖一些存储和中间件，为减小测试环境的部署成本，提供了一键部署的docker脚本。
在项目根目录下执行 `docker-compose up` 即可下载运行这些依赖。

**Comment by santosshen** [comment]
好的，看到了，感谢
