### ISSUE TITLE
docker-compose 中 logstash 默认配置错误

### ISSUE THREAD

**Issue by imp0wd3r** [0Kee-Team/WatchAD#7]
WatchAD/settings/logstash/logstash.conf

其中 Elasticsearch 和 Rabbitmq 的 host 都是 127.0.0.1，这样在 Docker 模式下， logstash 会去访问它容器内的端口，而不是访问实际服务的端口，这就导致直接使用`docker-compose up`来启动失效。

**Comment by Qianlitp** [comment]
目前已经将 `docker-compose.yaml` 文件中logstash启动的网络模式改为了 `host`，logstash将使用宿主机网络环境，可访问 127.0.0.1。

如有其它问题，欢迎继续反馈。
