### ISSUE TITLE
两处 Bug

### ISSUE THREAD

**Issue by imp0wd3r** [0Kee-Team/WatchAD#8]
https://github.com/0Kee-Team/WatchAD/blob/49a95af7ffe2d646bc8eb29f26ca89aa63e64dd9/WatchAD.py#L67

1. 最后的5应为字符串，否则会报如下错误：
![watchad-int](https://user-images.githubusercontent.com/17606044/68188698-b83ad300-ffe4-11e9-8e27-9dd04d5b228d.png)

2. `ENV_WATCHAD_ENGINE_NUM`前面的`ENV_`应该去掉，否则会报如下错误：
![watchad-env](https://user-images.githubusercontent.com/17606044/68188755-d1dc1a80-ffe4-11e9-88b5-142e89aa12fc.png)

**Comment by Qianlitp** [comment]
非常感谢你的反馈，我会尽快修改相关问题。

**Comment by Qianlitp** [comment]
我们已经在最新的提交中修复了这个问题。[15c1690](https://github.com/0Kee-Team/WatchAD/commit/15ce690a54b1e097643309855d478f07f22f4f36)
