### ISSUE TITLE
logstash修改配置后还是不能部署

### ISSUE THREAD

**Issue by wry5209** [0Kee-Team/WatchAD#9]
修改logstash配置，已经将服务地址配置为部署项目的服务器IP，但使用docker-compose up命令后还是不能部署logstash，报错信息：[WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error.

**Comment by Qianlitp** [comment]
非常感谢你的反馈。

你的ES是否启用了 xpack 安全插件，这样的话连接ES需要用户名和密码，导致logstash连接失败。
你可以在logstash的配置中指定用户名和密码，或者选择在 `docker-compose.yaml` 文件中的 watchad_elasticsearch -> environment 选项中增加一行：`xpack.security.enabled: "false"`，禁用xpack插件。

如果仍然没有解决你的问题，请回复我更详细的信息。
